### PR TITLE
Pull Request for #5: Develop GSLabMLE package

### PR DESCRIPTION
**Pull request by yuchuan2016**
@arosenbe , this is no hurry, but may take a decent amount of time. Basically this is a shortened "translation" from the original [MATLAB](https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/matlab/gslab_mle/) library. A lot of stuff in MLEEstimationOutput are missing, but I think this is sufficient for the first pass.

I also modified some code in GSLabModel library. Basically I switch from Knitro to optim as the optimization tool. Let me know if you have any question. Thanks!

### CODE REVIEW

**Comment by arosenbe** [comment]
Sorry @yuchuan2016, haven't started yet.

**Comment by arosenbe** [comment]
Starting on this now.

**Comment by arosenbe** [comment]
@yuchuan2016, I'm having trouble installing the GSLabMLE package. Any thoughts?

* From Github

screen shot 2017-10-25 at 2 23 27 pm

* From local repository

screen shot 2017-10-25 at 2 32 20 pm

**Comment by arosenbe** [comment]
Thanks for your help @yuchuan2016. I was missing our NumericalDerviatives packages. Installing that first made my installation successful. We'll want a way to install this dependency automatically (in the `DESCRIPTION` file, I think) so future users don't suffer the same issue.

A useful link for the automatic installation https://github.com/hadley/devtools/pull/902.

**Comment by arosenbe** [comment]
Sorry @yuchuan2016, no work yet 🙁

**Comment by yuchuan2016** [comment]
@arosenbe , no worry! This is of low priority.

**Comment by arosenbe** [comment]
Still no work.

**Comment by arosenbe** [comment]
Still no work

**Comment by arosenbe** [comment]
I've started looking at code, but haven't had time to make much progress yet. Quality seems high so far.

**Comment by arosenbe** [comment]
I've gotten through the modification to gslab model. Now ready to start on MLE.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
No work done since last comment.

**Comment by arosenbe** [comment]
I think it will be *much* more efficient if @z-y-huang takes over.

**Comment by z-y-huang** [comment]
Haven't started yet.

**Comment by z-y-huang** [comment]
Haven't started yet.

**Comment by z-y-huang** [comment]
Haven't started yet.

**Comment by DavidRitzwoller** [comment]
@z-y-huang. I assume you don't mind if I take this over?

**Comment by z-y-huang** [comment]
@DavidRitzwoller:

Nope!

**Comment by DavidRitzwoller** [comment]
No work in past 2 weeks

**Comment by DavidRitzwoller** [comment]
No work in past 2 weeks

**Comment by DavidRitzwoller** [comment]
No work in past 2 weeks

**Comment by DavidRitzwoller** [comment]
No work in past 2 weeks

**Comment by DavidRitzwoller** [comment]
No work in past 2 weeks

**Comment by DavidRitzwoller** [comment]
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3ADavidRitzwoller+updated%3A%3C2019-08-05+

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
@gentzkow. This PR has been stale for quite a while. Our sense has been that a PR would require a substantial time investment, and we haven't had the bandwidth to carve that out. 

Do you have any thoughts for how we should proceed?

**Comment by gentzkow** [comment]
Ooh. Let's definitely find a way to close it out with minimal effort.

**Comment by DavidRitzwoller** [comment]
@gentzkow. The code is organized, well-documented, and all the tests pass. So I'd think we could merge to master and make a note on #5 that the complete code base hasn't been double checked carefully.

**Comment by gentzkow** [comment]
perfect

**Pull request merged**
