### PR TITLE
Development loadpaths

### PR DESCRIPTION
**Pull request by arosenbe**
@lboxell Can you check over the proposed workflow in the top-level `README`? The format/workflow I propose follows R package development, but it doesn't make use of make.py.

@Shun-Yang Please check the proposed workflow and the code/format of `loadpaths`. Try `devtools::check` to see if you can pass the unit tests. 

The task deliverable is [here](https://github.com/gslab-econ/admin/blob/89ba90d7c850abe092b735384f0a2ab5290311aa/issues/16/admin-16.md) in the admin repo.

### CODE REVIEW

**Comment by lboxell** [comment]
@arosenbe,

It looks like some of the markdown links aren't working in the 'Overview' section of the readme and a few other places (I'd be fine just text referencing, no link, if thats easiest). 

I'm not sure "We use two primary branches on gslab_r for each package: master and development-packagename" is how we want to phrase this. I think we use a single master branch and then a development branch for each package.

It might be good to have a very simple example under 'Development Process'. So `cd REPO`, edit function, `document`, etc. and then I'd maybe move these up to the top of the readme so I reader doesn't have to read everything to figure out how to run the directory and/or install the packages.

**Comment by arosenbe** [comment]
@lboxell, I've updated the [README](https://github.com/gslab-econ/gslab_r/blob/e6aa2c06b34a353ce1d511399b81958fecaec40f/README.md). Could you take a look when you get a chance?

**Comment by lboxell** [comment]
@arosenbe,
 Seems fine to me. @Shun-Yang should make sure he agrees with it too after PR'ing the rest of this.

**Comment by arosenbe** [comment]
Note to self, once we have completed gslab-econ/admin#17, we can resolve the conflict with this pull request.

**Pull request merged**
