### PR TITLE
Pull Request for #12: Allow flexible sorting with SaveData()

### PR DESCRIPTION
**Pull request by veli-m-andirin**
Hi @yu-jia-wang!

Could you please confirm the following:

- We now have the option to not to sort the data based on keys, i.e. we can save data that is sorted differently.
- We can now compute the means of numeric variables even when there are missing values.
- The default appendlog option is now FALSE.

These changes should also be correctly reflected in `SaveData/man/SaveData.Rd` and `SaveData/tests/testthat/test-SaveData.r`.

Thank you!

### CODE REVIEW

**Review by yu-jia-wang — APPROVED** [review]
Hi @veli-m-andirin I have reviewed the package and can confirm the goals listed [here](https://github.com/gslab-econ/gslab_r/pull/13#issue-969320160) are completed.

One thing I wanted to flag, which may lie outside the scope of the pull/issue, is `Checkkey` currently handles `NA` in key as a unique value. As a result,
1. If there is one observation with missing key, `SaveData` keeps it and proceeds as usual;
2. If there are multiple observations with missing key, `SaveData` proceeds with the non-unique key scenario and returns the error `KeyError: Key variables do not uniquely identify observations.`

This may be suboptimal since a message of non-unique key conveys different information than missing keys.  IMHO perhaps we could drop observations with missing keys, and return a warning message stating exactly how many of observations were dropped because of that?

@jmshapir FYI

**Comment by veli-m-andirin** [comment]
Thanks @yu-jia-wang, great point!

Another solution could be to have an option where we can specify whether or not we want to allow missing keys, as in the Stata version of `save_data`. 

We can actually build another version of this option where we'd have flexibility to:

1) Raise an error message when there are missing key values.
2) Accept missing keys.
3) Drop observations with missing keys and raise a warning.

**Comment by jmshapir** [comment]
Thanks @yu-jia-wang @veli-m-andirin!

I think the behavior we want is that if there is a missing value of the key, the command just breaks and throws an error.

I defer to you both on whether to implement here or in a separate issue.

**Comment by yu-jia-wang** [comment]
Thanks @jmshapir! @veli-m-andirin I'd vote we tackle it here but let me know if you see it differently!

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir!

@yu-jia-wang, I implemented @jmshapir's suggestion and added a test for it. Could you look at the changes in this branch again and let me know if they look correct to you?

**Comment by yu-jia-wang** [comment]
Thanks @veli-m-andirin! The changes look good to me. I added two pieces in https://github.com/gslab-econ/gslab_r/pull/13/commits/e03c3db4fab2358648b07aa27bb202282bc23260 to
1. Spot `NA` when the key is string–sometimes R will read missing value in a string variable as empty string (`""`), causing failure to detect missing keys.
2. Report the keys with missing value along in the error message.

If you agree with the changes I believe we're good to merge. But let me know if you spot any problems otherwise!

**Comment by veli-m-andirin** [comment]
Thanks @yu-jia-wang! On the points in https://github.com/gslab-econ/gslab_r/pull/13#issuecomment-903265835:

1. I  wouldn't think R will read missing value as `""` unless we tell it specifically to do so.  `NA` is the standard way of representing missing value for character data types as well.  There might be cases where external data uses `""` or something else (e.g. `"."`, "-") to represent missing values, but when reading such data, one tells (or should tell) R how missing values are represented, as in `read.csv` or `read_csv`. Likewise, one can tell how they want to represent `NA` values when exporting data. However, when working in R, I guess `NA` is the standard. 

I'd understand that for some reason, it might be desirable to use something else for missing values, (`""`, `"."`, `"-"`, etc.), but I don't think we'd want to account for these specific cases. `""`, ``"."`, or `"-"` might indeed be a valid identifier in some other rare cases, and I'd hesitate to claim these as missing values.

Please let me know what you think.

2. Looks good to me!

**Comment by yu-jia-wang** [comment]
Thanks @veli-m-andirin! 

I think you're right that `NA` is standard for `read_csv` and perhaps for most of R applications. Below are the exact steps of my little experiment:
1. Generate a `pandas.DataFrame` in python, where the key is string;
2. Replace one value of the key with missing value (`numpy.nan`);
3. Export it to CSV;
4. read it into R using `data.table::fread()` (which is generally faster esp. for large data sets, and is used extensively in one of our repos)
5. The missing value appears as empty string `""`, and `is.na()` returns `FALSE`.

Above is just to explain why I flagged this issue in the [previous comment](https://github.com/gslab-econ/gslab_r/pull/13#issuecomment-903265835)–`read_csv()` will read them as the standard `NA`. 

> I'd understand that for some reason, it might be desirable to use something else for missing values, ("", ".", "-", etc.), but I don't think we'd want to account for these specific cases. "", ``".", or "-"` might indeed be a valid identifier in some other rare cases, and I'd hesitate to claim these as missing values.

This makes perfect sense to me! I agree we should remove the line below and leave it to the user to decide whether `""` is missing value or valid identifier.
```r
for (k in key) { df[[k]][data[[k]] == ""] <- NA }
```

**Comment by veli-m-andirin** [comment]
Thanks @yu-jia-wang!

On https://github.com/gslab-econ/gslab_r/pull/13#issuecomment-903291071: Yes, I agree that `data.table` package is great for speed! I think `na.strings` option in `fread` could be used in that case per [here](https://www.rdocumentation.org/packages/data.table/versions/1.14.0/topics/fread). Per the documentation there, it actually reads `",,"` as `NA` as well. It only reads `,"",` as `""`, because it considers it as an unambiguous case. If in that specific application these values (or something else) correspond to `NA`s, then my choice would be to specify them using `na.strings`

On the following:

> This makes perfect sense to me! I agree we should remove the line below and leave it to the user to decide whether "" is missing value or valid identifier.

Done in 34891f6.

An additional point on 2 in https://github.com/gslab-econ/gslab_r/pull/13#issuecomment-903265835: When I tested the script with two keys that had missing values, I got this message: "  KeyError: There are rows with missing keys (a).KeyError: There are rows with missing keys (b)." 

I modified it to print: "  KeyError: There are rows with missing keys. Check the following keys: a, b"

I tested `SaveData` once again after this and ran the unit tests, I think everything looks good. If you agree, I'll proceed with squash-and-merge.

**Comment by yu-jia-wang** [comment]
Thanks @veli-m-andirin the changes look great! (P.S. I find the below very helpful!)
> On #13 (comment): Yes, I agree that data.table package is great for speed! I think na.strings option in fread could be used in that case per here. Per the documentation there, it actually reads ",," as NA as well. It only reads ,"", as "", because it considers it as an unambiguous case. If in that specific application these values (or something else) correspond to NAs, then my choice would be to specify them using na.strings

**Comment by veli-m-andirin** [comment]
Summary [here](https://github.com/gslab-econ/gslab_r/issues/12#issuecomment-903764159).

**Pull request merged**
